### ISSUE TITLE
Corn not rendering

### ISSUE THREAD

**Issue by WesCook** [cleverpanda/SimpleCorn#5]
On the plus side, I'm happy to see 16x16 graphics.

On the down side, they're a bit *vibrant*.

![safe_to_eat](https://cloud.githubusercontent.com/assets/792101/24131901/a8727566-0dae-11e7-9739-56c078209d05.png)

I think you have an incorrect MRL set somewhere.  ;)

**Comment by cleverpanda** [comment]
Wot. MC version, SC version?
That's weird because I tested it and also there's no black in those images...

**Comment by WesCook** [comment]
* Minecraft v1.10.2
* SimpleCorn v2.1.0

This was from a newly generated world and config file.

I should also note that the icons in JEI show as purple.

---

Relevant log errors:

Blockmodel

```
[09:24:19] [Client thread/ERROR]: Exception loading model for variant simplecorn:corn#inventory, normal location exception: 
net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model simplecorn:item/corn with loader VanillaLoader.INSTANCE, skipping
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) ~[ModelLoaderRegistry.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177590_d(ModelLoader.java:328) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177577_b(ModelBakery.java:170) ~[byo.class:?]
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:148) ~[ModelLoader.class:?]
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) [byp.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122) [bxi.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.io.FileNotFoundException: simplecorn:models/item/corn.json
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) ~[bww.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[bxi.class:?]
	at net.minecraft.client.renderer.block.model.ModelBakery.func_177594_c(ModelBakery.java:311) ~[byo.class:?]
	at net.minecraftforge.client.model.ModelLoader.access$1100(ModelLoader.java:118) ~[ModelLoader.class:?]
	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:879) ~[ModelLoader$VanillaLoader.class:?]
	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) ~[ModelLoaderRegistry.class:?]
	... 14 more
```

Textures

```
[09:25:05] [Client thread/ERROR]: Using missing texture, unable to load simplecorn:textures/items/cornItem.png, java.io.FileNotFoundException

[09:25:06] [Client thread/ERROR]: Using missing texture, unable to load simplecorn:textures/blocks/Corn_11.png, java.io.FileNotFoundException
[09:25:06] [Client thread/ERROR]: Using missing texture, unable to load simplecorn:textures/blocks/Corn_12.png, java.io.FileNotFoundException
[09:25:06] [Client thread/ERROR]: Using missing texture, unable to load simplecorn:textures/blocks/Corn_10.png, java.io.FileNotFoundException
```

**Comment by cleverpanda** [comment]
[SimpleCorn1.10-2.1.1.zip](https://github.com/cleverpanda/SimpleCorn/files/859663/SimpleCorn1.10-2.1.1.zip)

Try this for me. jar is in the zip

**Comment by WesCook** [comment]
No bueno.  Still getting the same missing textures/models.

I think I see what the problem is though.  In the log above, the item names are `/blocks/Corn_11.png`.  Looking inside the .jar, the files are named `/blocks/corn_11.png`.  Capitalization does not match.

It sounds like you couldn't reproduce the issue on your end.  Maybe we're seeing some difference due to file system case sensitivity?  (Though I'm in Windows which is case-insensitive, so that'd be weird).

**Comment by cleverpanda** [comment]
I migrated this code from the 1.11 version I did, which is case sensitive, so it should have all matched.... ill take closer look

**Comment by cleverpanda** [comment]
2.1.0 had the old file structure so I assumed that was the issue. Apparently it was only part of it

**Comment by WesCook** [comment]
So I poked around to see if I could find the cause of the problem.  It seems only the 1.11 branch is on Github however, so I wasn't able to reproduce the problem.

But what I can tell from looking in the .jar is that it does seem to be the issue I described above.

/blockstates/corn.json has:
```
         "0":{  
            "textures":{  
               "crop": "simplecorn:blocks/Corn_1"
            }
         },
         ...
```
Yet the actual file is `/textures/blocks/corn_1.png`.

So it seems like a pretty simple fix, just update the references to all be lowercase.  Or am I missing something?

**Comment by cleverpanda** [comment]
![image](https://cloud.githubusercontent.com/assets/2975515/24415347/d1a7827a-13a6-11e7-94e2-8d6d0c49cecf.png)
Looks like yore right, I missed these. Testing

**Comment by cleverpanda** [comment]
As far as I can tell, V2.1.4 fixed it, can you download and confirm?

**Comment by WesCook** [comment]
It's better.  The actual corn block now works.  Once harvested the actual vegetable is missing its texture though.

Looking into JEI, both simplecorn:corncob and simplecorn:corn are purple squares.
